import type { UI } from "@/shared";

export const THEMES: UI.OptionGroup[] = [
	{
		label: "Motifs",
		options: [
			{ key: "advancedPawn", label: "Advanced pawn" },
			{ key: "attackingF2F7", label: "Attacking f2 or f7" },
			{ key: "capturingDefender", label: "Capturing defender" },
			{ key: "discoveredAttack", label: "Discovered attack" },
			{ key: "discoveredCheck", label: "Discovered check" },
			{ key: "doubleCheck", label: "Double check" },
			{ key: "exposedKing", label: "Exposed king" },
			{ key: "fork", label: "Fork" },
			{ key: "hangingPiece", label: "Hanging piece" },
			{ key: "kingsideAttack", label: "Kingside attack" },
			{ key: "pin", label: "Pin" },
			{ key: "queensideAttack", label: "Queenside attack" },
			{ key: "sacrifice", label: "Sacrifice" },
			{ key: "skewer", label: "Skewer" },
			{ key: "trappedPiece", label: "Trapped piece" },
		],
	},
	{
		label: "Advanced",
		options: [
			{ key: "attraction", label: "Attraction" },
			{ key: "clearance", label: "Clearance" },
			{ key: "defensiveMove", label: "Defensive move" },
			{ key: "deflection", label: "Deflection" },
			{ key: "interference", label: "Interference" },
			{ key: "intermezzo", label: "Intermezzo" },
			{ key: "quietMove", label: "Quiet move" },
			{ key: "xRayAttack", label: "X-ray attack" },
			{ key: "zugzwang", label: "Zugzwang" },
		],
	},
	{
		label: "Dev experiments",
		options: [
			{ key: "mateIn1", label: "Mate in 1" },
			{ key: "mateIn2", label: "Mate in 2" },
			{ key: "mateIn3", label: "Mate in 3" },
			{ key: "mateIn4", label: "Mate in 4" },
			{ key: "mateIn5", label: "Mate in 5" },
			{ key: "oneMove", label: "One move" },
			{ key: "short", label: "Short" },
			{ key: "long", label: "Long" },
			{ key: "veryLong", label: "Very Long" },
		],
	},
	{
		label: "Mate patterns",
		options: [
			{ key: "mate", label: "Mate" },
			{ key: "anastasiaMate", label: "Anastasia mate" },
			{ key: "arabianMate", label: "Arabian mate" },
			{ key: "backRankMate", label: "Back rank mate" },
			{ key: "balestraMate", label: "Balestra mate" },
			{ key: "blindSwineMate", label: "Blind Swine mate" },
			{ key: "bodenMate", label: "Boden's mate" },
			{ key: "cornerMate", label: "Corner mate" },
			{ key: "doubleBishopMate", label: "Double bishop mate" },
			{ key: "dovetailMate", label: "Dovetail mate" },
			{ key: "epauletteMate", label: "Epaulette mate" },
			{ key: "hookMate", label: "Hook mate" },
			{ key: "killBoxMate", label: "Kill box mate" },
			{ key: "pillsburysMate", label: "Pillsbury's mate" },
			{ key: "morphysMate", label: "Morphy's mate" },
			{ key: "operaMate", label: "Opera mate" },
			{ key: "swallowstailMate", label: "Swallow's Tail mate" },
			{ key: "triangleMate", label: "Triangle mate" },
			{ key: "smotheredMate", label: "Smothered mate" },
			{ key: "vukovicMate", label: "Vukovic mate" },
		],
	},
	{
		label: "Endgame",
		options: [
			{ key: "pawnEndgame", label: "Pawn endgame" },
			{ key: "knightEndgame", label: "Knight endgame" },
			{ key: "bishopEndgame", label: "Bishop endgame" },
			{ key: "rookEndgame", label: "Rook endgame" },
			{ key: "queenEndgame", label: "Queen endgame" },
			{ key: "queenRookEndgame", label: "Queen and rook endgame" },
		],
	},
	{
		label: "Phases",
		options: [
			{ key: "opening", label: "Opening" },
			{ key: "middlegame", label: "Middlegame" },
			{ key: "endgame", label: "Endgame" },
		],
	},
	{
		label: "Special moves",
		options: [
			{ key: "castling", label: "Castling" },
			{ key: "enPassant", label: "En passant" },
			{ key: "promotion", label: "Promotion" },
			{ key: "underPromotion", label: "Underpromotion" },
		],
	},
	{
		label: "Goals",
		options: [
			{ key: "equality", label: "Equality" },
			{ key: "advantage", label: "Advantage" },
			{ key: "crushing", label: "Crushing" },
		],
	},
	{
		label: "Origin",
		options: [
			{ key: "master", label: "Master games" },
			{ key: "masterVsMaster", label: "Master vs Master games" },
			{ key: "superGM", label: "Super GM games" },
		],
	},
];
