export const puzzleThemes = [
	{ value: "advancedPawn", text: "Advanced pawn" },
	{ value: "advantage", text: "Advantage" },
	{ value: "anastasiaMate", text: "Anastasia mate" },
	{ value: "arabianMate", text: "Arabian mate" },
	{ value: "attackingF2F7", text: "Attacking f2 or f7" },
	{ value: "attraction", text: "Attraction" },
	{ value: "backRankMate", text: "Back rank mate" },
	{ value: "bishopEndgame", text: "Bishop endgame" },
	{ value: "bodenMate", text: "Boden's mate" },
	{ value: "castling", text: "Castling" },
	{ value: "capturingDefender", text: "Capturing defender" },
	{ value: "crushing", text: "Crushing" },
	{ value: "doubleBishopMate", text: "Double bishop mate" },
	{ value: "dovetailMate", text: "Dovetail mate" },
	{ value: "equality", text: "Equality" },
	{ value: "kingsideAttack", text: "Kingside attack" },
	{ value: "clearance", text: "Clearance" },
	{ value: "defensiveMove", text: "Defensive move" },
	{ value: "deflection", text: "Deflection" },
	{ value: "discoveredAttack", text: "Discovered attack" },
	{ value: "doubleCheck", text: "Double check" },
	{ value: "endgame", text: "Endgame" },
	{ value: "exposedKing", text: "Exposed king" },
	{ value: "fork", text: "Fork" },
	{ value: "hangingPiece", text: "Hanging piece" },
	{ value: "hookMate", text: "Hook mate" },
	{ value: "interference", text: "Interference" },
	{ value: "intermezzo", text: "Intermezzo" },
	{ value: "killBoxMate", text: "Kill box mate" },
	{ value: "vukovicMate", text: "Vukovic mate" },
	{ value: "knightEndgame", text: "Knight endgame" },
	{ value: "master", text: "Master games" },
	{ value: "masterVsMaster", text: "Master vs Master games" },
	{ value: "mate", text: "Mate" },
	{ value: "mateIn1", text: "Mate in 1" },
	{ value: "mateIn2", text: "Mate in 2" },
	{ value: "mateIn3", text: "Mate in 3" },
	{ value: "mateIn4", text: "Mate in 4" },
	{ value: "mateIn5", text: "Mate in 5 or more" },
	{ value: "middlegame", text: "Middlegame" },
	{ value: "opening", text: "Opening" },
	{ value: "pawnEndgame", text: "Pawn endgame" },
	{ value: "pin", text: "Pin" },
	{ value: "promotion", text: "Promotion" },
	{ value: "queenEndgame", text: "Queen endgame" },
	{ value: "queenRookEndgame", text: "Queen and rook endgame" },
	{ value: "queensideAttack", text: "Queenside attack" },
	{ value: "quietMove", text: "Quiet move" },
	{ value: "rookEndgame", text: "Rook endgame" },
	{ value: "sacrifice", text: "Sacrifice" },
	{ value: "skewer", text: "Skewer" },
	{ value: "smotheredMate", text: "Smothered mate" },
	{ value: "superGM", text: "Super GM games" },
	{ value: "trappedPiece", text: "Trapped piece" },
	{ value: "underPromotion", text: "Underpromotion" },
	{ value: "xRayAttack", text: "X-ray attack" },
	{ value: "zugzwang", text: "Zugzwang" },
];
